/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 table.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const link = "https://cdn.jsdelivr.net/gh/Ilytar/models_poker@main/table.gltf";

export default function Table(props) {
    const { nodes, materials } = useGLTF(link);
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Cube.geometry}
                material={materials.table_material}
            />
        </group>
    );
}

useGLTF.preload(link);
